<?php

declare(strict_types=1);

namespace App\Enum;

enum AuditAction: string
{
    case USER_CREATED = 'USER_CREATED';
    case USER_UPDATED = 'USER_UPDATED';
    case USER_DEACTIVATED = 'USER_DEACTIVATED';
    case ROLE_ASSIGNED = 'ROLE_ASSIGNED';
    case ROLE_REVOKED = 'ROLE_REVOKED';
    case SESSION_CREATED = 'SESSION_CREATED';
    case SESSION_REVOKED = 'SESSION_REVOKED';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case STORE_CREATED = 'STORE_CREATED';
    case STORE_UPDATED = 'STORE_UPDATED';
    case STORE_SUSPENDED = 'STORE_SUSPENDED';
    case STORE_CLOSED = 'STORE_CLOSED';
    case REGION_CREATED = 'REGION_CREATED';
    case REGION_UPDATED = 'REGION_UPDATED';
    case REGION_CLOSED = 'REGION_CLOSED';
    case ZONE_CREATED = 'ZONE_CREATED';
    case ZONE_UPDATED = 'ZONE_UPDATED';
    case ZONE_DEACTIVATED = 'ZONE_DEACTIVATED';
    case WINDOW_CREATED = 'WINDOW_CREATED';
    case WINDOW_UPDATED = 'WINDOW_UPDATED';
    case WINDOW_DEACTIVATED = 'WINDOW_DEACTIVATED';
    case BOUNDARY_UPLOADED = 'BOUNDARY_UPLOADED';
    case BOUNDARY_VALIDATED = 'BOUNDARY_VALIDATED';
    case BOUNDARY_APPLIED = 'BOUNDARY_APPLIED';
    case CONTENT_CREATED = 'CONTENT_CREATED';
    case CONTENT_PUBLISHED = 'CONTENT_PUBLISHED';
    case CONTENT_UPDATED = 'CONTENT_UPDATED';
    case CONTENT_ROLLED_BACK = 'CONTENT_ROLLED_BACK';
    case CONTENT_ARCHIVED = 'CONTENT_ARCHIVED';
    case SENSITIVE_FIELD_ACCESSED = 'SENSITIVE_FIELD_ACCESSED';
    case EXPORT_REQUESTED = 'EXPORT_REQUESTED';
    case EXPORT_COMPLETED = 'EXPORT_COMPLETED';
    case RETENTION_EXECUTED = 'RETENTION_EXECUTED';
    case KEY_ROTATED = 'KEY_ROTATED';
}
